---
defconfig_name: "mscc_stage1_servalt_defconfig"
append_files:
    - config_file: "configs/mscc_stage1_servalt_defconfig"
      files:
        - br_target_mips.config
        - br_target_stage1.config
        - br_toolchain_mips_uclib.config
        - br_uboot.config
        - br_board_servalt.config
        - br_linux.config
        - br_tuning.config
    - config_file: "board/servalt/servalt_kernel.config"
      files:
        - linux.config
        - linux_iptables.config
        - linux_servalt.config
    - config_file: "board/servalt/servalt_uboot.config"
      files:
        - uboot_servalt.config
output_packet: "mscc-brsdk-mipsel"
output_path: "mipsel-mips32r2-linux-uclibc/servalt"
uboot_name: "uboot_servalt.bin"
arch: "mips"
