---
defconfig_name: "mscc_stage1_serval1_defconfig"
append_files:
    - config_file: "configs/mscc_stage1_serval1_defconfig"
      files:
        - br_target_mips.config
        - br_target_stage1.config
        - br_toolchain_mips_uclib.config
        - br_uboot.config
        - br_board_serval1.config
        - br_linux.config
        - br_tuning.config
    - config_file: "board/serval1/serval1_kernel.config"
      files:
        - linux.config
        - linux_iptables.config
        - linux_serval1.config
    - config_file: "board/serval1/serval1_uboot.config"
      files:
        - uboot_serval1.config
output_packet: "mscc-brsdk-mipsel"
output_path: "mipsel-mips32r2-linux-uclibc/serval1"
uboot_name: "uboot_serval1.bin"
arch: "mips"
